[package]
name = "advent2015"
version = "0.1.0"
authors = ["Nick Meyer <nick@e3b0c442.io>"]
edition = "2018"
default-run = "advent2015"

[dependencies]
simple-error = "0.2"
md-5 = "0.9"
lazy_static = "1"
regex = "1"